install.packages("tidyverse", dep = TRUE)
## COMANDO PARA INSTALAR PROGRAMAS, DEP = TRUE ES PARA QUE PUEDA DESCARGAR PAQUETES ASOCIADOS

library(tidyverse)

## PARA CARGAR PAQUETES (TODAS LAS VECES QUE ABRES RSTUDIO HAY QUE CARGAR PAQUETES)
## TAMBIEN SE PUEDE HACER CON EL RATÓN BUSCANDO EL PAQUETE Y MARCANDO EL TICK

install.packages("magic", dep = TRUE)

library(magic)

magic(6)
 